
ALTER TABLE public.promo_panels
  ADD COLUMN IF NOT EXISTS title TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS subtitle TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS cta_text TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS bg_image_url TEXT,
  ADD COLUMN IF NOT EXISTS gradient TEXT NOT NULL DEFAULT 'from-gray-900 via-gray-800 to-gray-900';
